import { hashSync } from 'bcrypt-ts-edge'

const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: hashSync('123456', 10),
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
    {
      name: 'glenn',
      email: 'noexgp@gmai.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
  ],

  products: [
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        'https://utfs.io/f/uITW2xeNKaS1pwACw6813HLaqv7uj6VhGtcfTSR82pKFBxIJ',
        'https://utfs.io/f/uITW2xeNKaS169gKNRHlmFibZnwpfNoI7MyWQ0LPBSOtjVDg',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        'https://utfs.io/f/uITW2xeNKaS1kTK8I1zuU1za6I0qgvlYRxBSw8QDKphnWLNM',
        'https://utfs.io/f/uITW2xeNKaS1iKHP1WR3CUgq2s3rRuod0bELk4eMjDHfAynJ',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        'https://utfs.io/f/uITW2xeNKaS1AQQn1AKiBJYp0bZ4nO3toL178lH9VDWcPTz2',
        'https://utfs.io/f/uITW2xeNKaS1VYOo3KpmrX2Np0VZQxtd3vMzB4ijI6OFSAWH',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        'https://utfs.io/f/uITW2xeNKaS1ix1EqU3CUgq2s3rRuod0bELk4eMjDHfAynJi',
        'https://utfs.io/f/uITW2xeNKaS17I62P3lXkDsoQWh8CwqAMR0aOxbzSut4nci1',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        'https://utfs.io/f/uITW2xeNKaS1kYxLsOUzuU1za6I0qgvlYRxBSw8QDKphnWLN',
        'https://utfs.io/f/uITW2xeNKaS171BZHmlXkDsoQWh8CwqAMR0aOxbzSut4nci1',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        'https://utfs.io/f/uITW2xeNKaS1ZLPKKk69C8Dn7xKsR0MStGf5PqAIXBaOLTzb',
        'https://utfs.io/f/uITW2xeNKaS1KZEUvKnI0Vp9yInlT7WmBN2PcFkroCX81ji4',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
}

export default sampleData
